### ISSUE TITLE
bin EADDRNOTAVAIL

### ISSUE THREAD

**Issue by nullivex** [mgesmundo/multicast-events#1]
Hello,

I am trying to transition to this package and running into some issues.

I have created a simple test case and am receiving the following error:

```
node test

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: bind EADDRNOTAVAIL
    at errnoException (dgram.js:457:11)
    at dgram.js:210:28
    at dns.js:72:18
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:906:3
```

Here is my test code.

``` js
'use strict';
var Multicast = require('multicast-events').EventEmitter


var mcast = new Multicast({
  name: 'test',
  id: 'oose'
  //group: '226.0.0.1',
  //port: '3000'
})

mcast.on('foo',function(msg,rinfo){
  console(msg,rinfo)
})

mcast.emit('foo',{foo: 'bar'})
```

I have had my own multicast helper working on Windows so I am confused why I am seeing this error. I have tried many config variations with the same result.

Any help would be appreciated!

Thanks

**Comment by nullivex** [comment]
Here is the error with debug output.

```
node test
  events test new event emitter of the group 239.22.144.139 +0ms
  events test add listener ('function (msg,rinfo){ console(.') for "foo" event to 239.22.144.139:3820 +5ms
  events test ready to emit event of the group 239.22.144.139 +4ms

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: bind EADDRNOTAVAIL
    at errnoException (dgram.js:457:11)
    at dgram.js:210:28
    at dns.js:72:18
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by mgesmundo** [comment]
Hi,
what version of node and windows? I'm working on Mac/Linux :-)
Marcello

**Comment by nullivex** [comment]
Windows 7 64bit
Node 0.10.31

It only happens when setup a listener. I can emit just fine.

**Comment by mgesmundo** [comment]
Ok. I need to setup a windows virtual machine to try in the same your environment.

**Comment by majong** [comment]
I meet this issue too, when trying to run app1.js  in example folder.

Originally, I used it on nodejs v0.8.12, error report about stream module problem. Then I install nodeJS v0.10.33, but got the EADDRNOTAVAIL error.
